runtime: php73
env: flex

runtime_config:
 document_root: public

skip_files:
  .env

# env_variables:
#   APP_NAME: 'Jingga Teknologi'
#   APP_ENV: local
#   APP_KEY: 'base64:CVc/3k9Ow7nQq/oyzqr7dmKD3NnicZKuLu1RB2BqjJk:'

#   DB_CONNECTION: mysql
#   DB_HOST: 34.143.135.10
#   DB_PORT: 3306
#   DB_DATABASE: jingga_teknologi
#   DB_USERNAME: root
#   DB_PASSWORD: pepengkolan1

#   ZOOM_CLIENT_KEY: YWqFsLLtQ5KE-msTK3xWdQ
#   ZOOM_CLIENT_SECRET: hfXBmTkDwjxuhjkOTZxQp90BV0m7y5Raalft

#   BROADCAST_DRIVER: log
#   CACHE_DRIVER: file
#   FILESYSTEM_DISK: s3
#   QUEUE_CONNECTION: sync
#   SESSION_DRIVER: file
#   SESSION_LIFETIME: 120

#   MAIL_DRIVER: smtp
#   MAIL_HOST: smtp-relay.sendinblue.com
#   MAIL_PORT: 587
#   MAIL_USERNAME: gekikara404@gmail.com
#   MAIL_PASSWORD: wqtZChGpbIjNBrTA
#   MAIL_ENCRYPTION: tls
#   MAIL_FROM_ADDRESS: gekikara404@gmail.com
#   MAIL_FROM_NAME: '${APP_NAME}'

#   AWS_ACCESS_KEY_ID: AKIAU3FVKFJOXPUSVBFM
#   AWS_SECRET_ACCESS_KEY: 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
#   AWS_DEFAULT_REGION: ap-southeast-1
#   AWS_BUCKET: digital-survey